port 1194
proto udp
dev tun
ca /etc/openvpn/ca.crt
cert /etc/openvpn/r4.crt
key /etc/openvpn/r4.key
dh /etc/openvpn/dh.pem
server 10.160.8.0 255.255.255.0
ifconfig-pool-persist /etc/openvpn/ipp.txt

keepalive 5 150
status /var/log/openvpn/openvpn-status.log
log /var/log/openvpn/openvpn.log
verb 5

push "route 10.160.2.0 255.255.255.0"

client-config-dir /etc/openvpn/ccd
route 10.160.1.0 255.255.255.0 10.160.8.1

client-to-client
push "route 10.160.1.0 255.255.255.0"
